// @generated by protoc-gen-es v2.13.0 with parameter "target=js"
// @generated from file pong/v1/pong.proto (package pong.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file pong/v1/pong.proto.
 */
export const file_pong_v1_pong = /*@__PURE__*/
  fileDesc("ChJwb25nL3YxL3BvbmcucHJvdG8SB3BvbmcudjEiZwoNQ2xpZW50TWVzc2FnZRIkCgRqb2luGAEgASgLMhQucG9uZy52MS5Kb2luUmVxdWVzdEgAEiUKBWlucHV0GAIgASgLMhQucG9uZy52MS5QYWRkbGVJbnB1dEgAQgkKB3BheWxvYWQiHgoLSm9pblJlcXVlc3QSDwoHZ2FtZV9pZBgBIAEoCSI0CgtQYWRkbGVJbnB1dBIlCglkaXJlY3Rpb24YASABKA4yEi5wb25nLnYxLkRpcmVjdGlvbiKQAQoNU2VydmVyTWVzc2FnZRInCgZqb2luZWQYASABKAsyFS5wb25nLnYxLkpvaW5SZXNwb25zZUgAEiMKBXN0YXRlGAIgASgLMhIucG9uZy52MS5HYW1lU3RhdGVIABImCgVlcnJvchgDIAEoCzIVLnBvbmcudjEuRXJyb3JNZXNzYWdlSABCCQoHcGF5bG9hZCI1CgxKb2luUmVzcG9uc2USDwoHZ2FtZV9pZBgBIAEoCRIUCgxwbGF5ZXJfaW5kZXgYAiABKAUicQoJR2FtZVN0YXRlEg4KBmJhbGxfeBgBIAEoARIOCgZiYWxsX3kYAiABKAESEQoJcGFkZGxlMV95GAMgASgBEhEKCXBhZGRsZTJfeRgEIAEoARIOCgZzY29yZTEYBSABKAUSDgoGc2NvcmUyGAYgASgFIh8KDEVycm9yTWVzc2FnZRIPCgdtZXNzYWdlGAEgASgJKmAKCURpcmVjdGlvbhIZChVESVJFQ1RJT05fVU5TUEVDSUZJRUQQABIQCgxESVJFQ1RJT05fVVAQARISCg5ESVJFQ1RJT05fRE9XThACEhIKDkRJUkVDVElPTl9TVE9QEAMySQoLUG9uZ1NlcnZpY2USOgoEUGxheRIWLnBvbmcudjEuQ2xpZW50TWVzc2FnZRoWLnBvbmcudjEuU2VydmVyTWVzc2FnZSgBMAFCNVozZ2l0aHViLmNvbS9nZW9mcHdoaXRlL2h0bWxfZ2FtZXNfZW5naW5lL3BvbmcvcG9uZ3YxYgZwcm90bzM");

/**
 * Describes the message pong.v1.ClientMessage.
 * Use `create(ClientMessageSchema)` to create a new message.
 */
export const ClientMessageSchema = /*@__PURE__*/
  messageDesc(file_pong_v1_pong, 0);

/**
 * Describes the message pong.v1.JoinRequest.
 * Use `create(JoinRequestSchema)` to create a new message.
 */
export const JoinRequestSchema = /*@__PURE__*/
  messageDesc(file_pong_v1_pong, 1);

/**
 * Describes the message pong.v1.PaddleInput.
 * Use `create(PaddleInputSchema)` to create a new message.
 */
export const PaddleInputSchema = /*@__PURE__*/
  messageDesc(file_pong_v1_pong, 2);

/**
 * Describes the message pong.v1.ServerMessage.
 * Use `create(ServerMessageSchema)` to create a new message.
 */
export const ServerMessageSchema = /*@__PURE__*/
  messageDesc(file_pong_v1_pong, 3);

/**
 * Describes the message pong.v1.JoinResponse.
 * Use `create(JoinResponseSchema)` to create a new message.
 */
export const JoinResponseSchema = /*@__PURE__*/
  messageDesc(file_pong_v1_pong, 4);

/**
 * Describes the message pong.v1.GameState.
 * Use `create(GameStateSchema)` to create a new message.
 */
export const GameStateSchema = /*@__PURE__*/
  messageDesc(file_pong_v1_pong, 5);

/**
 * Describes the message pong.v1.ErrorMessage.
 * Use `create(ErrorMessageSchema)` to create a new message.
 */
export const ErrorMessageSchema = /*@__PURE__*/
  messageDesc(file_pong_v1_pong, 6);

/**
 * Describes the enum pong.v1.Direction.
 */
export const DirectionSchema = /*@__PURE__*/
  enumDesc(file_pong_v1_pong, 0);

/**
 * @generated from enum pong.v1.Direction
 */
export const Direction = /*@__PURE__*/
  tsEnum(DirectionSchema);

/**
 * PongService is a real-time pong game mode. Unlike the other game modes
 * (which broadcast a JSON snapshot over a plain websocket whenever a move
 * comes in), pong needs a ball that keeps moving between inputs, so each
 * player holds one long-lived bidirectional stream: input flows up as the
 * player moves their paddle, and the server pushes a state snapshot down
 * on every physics tick regardless of whether the player has sent anything.
 *
 * @generated from service pong.v1.PongService
 */
export const PongService = /*@__PURE__*/
  serviceDesc(file_pong_v1_pong, 0);

