services:
  db:
    image: ghcr.io/geofpwhite/html_games_engine-db:latest
    container_name: db
    environment:
      - POSTGRES_PASSWORD=app
      - POSTGRES_USER=app
      - POSTGRES_DB=accounts
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./accounts/sql/schema.sql:/docker-entrypoint-initdb.d/db_setup.sql
      - ./accounts/sql/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: unless-stopped

  games-engine:
    image: ghcr.io/geofpwhite/html_games_engine:latest
    container_name: games-engine
    restart: always
    environment:
      - DATABASE_URL=postgresql://app:app@db:5432/accounts?sslmode=disable
      - REDIS_ADDR=redis:6379
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    depends_on:
      - games-engine
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_SERVER_ROOT_URL=https://geof.geofpwhite.us/metrics/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
      - loki
    ports:
      - "3000:3000"
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/snap/docker/common/var-lib-docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  db-data:
  prometheus-data:
  grafana-data:
  loki-data:
