// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pong/v1/pong.proto

package pongv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pongv1 "github.com/geofpwhite/html_games_engine/pong/pongv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PongServiceName is the fully-qualified name of the PongService service.
	PongServiceName = "pong.v1.PongService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PongServicePlayProcedure is the fully-qualified name of the PongService's Play RPC.
	PongServicePlayProcedure = "/pong.v1.PongService/Play"
)

// PongServiceClient is a client for the pong.v1.PongService service.
type PongServiceClient interface {
	Play(context.Context) *connect.BidiStreamForClient[pongv1.ClientMessage, pongv1.ServerMessage]
}

// NewPongServiceClient constructs a client for the pong.v1.PongService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPongServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PongServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pongServiceMethods := pongv1.File_pong_v1_pong_proto.Services().ByName("PongService").Methods()
	return &pongServiceClient{
		play: connect.NewClient[pongv1.ClientMessage, pongv1.ServerMessage](
			httpClient,
			baseURL+PongServicePlayProcedure,
			connect.WithSchema(pongServiceMethods.ByName("Play")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pongServiceClient implements PongServiceClient.
type pongServiceClient struct {
	play *connect.Client[pongv1.ClientMessage, pongv1.ServerMessage]
}

// Play calls pong.v1.PongService.Play.
func (c *pongServiceClient) Play(ctx context.Context) *connect.BidiStreamForClient[pongv1.ClientMessage, pongv1.ServerMessage] {
	return c.play.CallBidiStream(ctx)
}

// PongServiceHandler is an implementation of the pong.v1.PongService service.
type PongServiceHandler interface {
	Play(context.Context, *connect.BidiStream[pongv1.ClientMessage, pongv1.ServerMessage]) error
}

// NewPongServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPongServiceHandler(svc PongServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pongServiceMethods := pongv1.File_pong_v1_pong_proto.Services().ByName("PongService").Methods()
	pongServicePlayHandler := connect.NewBidiStreamHandler(
		PongServicePlayProcedure,
		svc.Play,
		connect.WithSchema(pongServiceMethods.ByName("Play")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pong.v1.PongService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PongServicePlayProcedure:
			pongServicePlayHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPongServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPongServiceHandler struct{}

func (UnimplementedPongServiceHandler) Play(context.Context, *connect.BidiStream[pongv1.ClientMessage, pongv1.ServerMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("pong.v1.PongService.Play is not implemented"))
}
