// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	Userid    int32
	Username  string
	Password  string
	Createdat pgtype.Date
}
