// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    Users (Username, Password)
VALUES
    ($1, $2)
RETURNING
    UserID
`

type CreateUserParams struct {
	Username string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password)
	var userid int32
	err := row.Scan(&userid)
	return userid, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM Users
WHERE
    UserID = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userid int32) error {
	_, err := q.db.Exec(ctx, deleteUser, userid)
	return err
}

const getUser = `-- name: GetUser :one
SELECT
    UserID,
    Username,
    Password
FROM
    Users
WHERE
    UserID = $1
`

type GetUserRow struct {
	Userid   int32
	Username string
	Password string
}

func (q *Queries) GetUser(ctx context.Context, userid int32) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, userid)
	var i GetUserRow
	err := row.Scan(&i.Userid, &i.Username, &i.Password)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    UserID,
    Username,
    Password
FROM
    Users
WHERE
    Username = $1
`

type GetUserByUsernameRow struct {
	Userid   int32
	Username string
	Password string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.Userid, &i.Username, &i.Password)
	return i, err
}

const getUsernames = `-- name: GetUsernames :many
SELECT
    Username
FROM
    Users
`

func (q *Queries) GetUsernames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getUsernames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE Users
SET
    Password = $2
WHERE
    UserID = $1
`

type UpdateUserPasswordParams struct {
	Userid   int32
	Password string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Userid, arg.Password)
	return err
}
