// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pong/v1/pong.proto

package pongv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_UP          Direction = 1
	Direction_DIRECTION_DOWN        Direction = 2
	Direction_DIRECTION_STOP        Direction = 3
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_UP",
		2: "DIRECTION_DOWN",
		3: "DIRECTION_STOP",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_UP":          1,
		"DIRECTION_DOWN":        2,
		"DIRECTION_STOP":        3,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_pong_v1_pong_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_pong_v1_pong_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_pong_v1_pong_proto_rawDescGZIP(), []int{0}
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Join
	//	*ClientMessage_Input
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_pong_v1_pong_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pong_v1_pong_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_pong_v1_pong_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetJoin() *JoinRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *ClientMessage) GetInput() *PaddleInput {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Input); ok {
			return x.Input
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Join struct {
	Join *JoinRequest `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type ClientMessage_Input struct {
	Input *PaddleInput `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

func (*ClientMessage_Join) isClientMessage_Payload() {}

func (*ClientMessage_Input) isClientMessage_Payload() {}

// JoinRequest must be the first message sent on the stream. game_id empty
// starts a new game; non-empty joins an existing one as the second player.
type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_pong_v1_pong_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pong_v1_pong_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_pong_v1_pong_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type PaddleInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     Direction              `protobuf:"varint,1,opt,name=direction,proto3,enum=pong.v1.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaddleInput) Reset() {
	*x = PaddleInput{}
	mi := &file_pong_v1_pong_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaddleInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaddleInput) ProtoMessage() {}

func (x *PaddleInput) ProtoReflect() protoreflect.Message {
	mi := &file_pong_v1_pong_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaddleInput.ProtoReflect.Descriptor instead.
func (*PaddleInput) Descriptor() ([]byte, []int) {
	return file_pong_v1_pong_proto_rawDescGZIP(), []int{2}
}

func (x *PaddleInput) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Joined
	//	*ServerMessage_State
	//	*ServerMessage_Error
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_pong_v1_pong_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pong_v1_pong_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_pong_v1_pong_proto_rawDescGZIP(), []int{3}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetJoined() *JoinResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Joined); ok {
			return x.Joined
		}
	}
	return nil
}

func (x *ServerMessage) GetState() *GameState {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Joined struct {
	Joined *JoinResponse `protobuf:"bytes,1,opt,name=joined,proto3,oneof"`
}

type ServerMessage_State struct {
	State *GameState `protobuf:"bytes,2,opt,name=state,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *ErrorMessage `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ServerMessage_Joined) isServerMessage_Payload() {}

func (*ServerMessage_State) isServerMessage_Payload() {}

func (*ServerMessage_Error) isServerMessage_Payload() {}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerIndex   int32                  `protobuf:"varint,2,opt,name=player_index,json=playerIndex,proto3" json:"player_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_pong_v1_pong_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pong_v1_pong_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_pong_v1_pong_proto_rawDescGZIP(), []int{4}
}

func (x *JoinResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *JoinResponse) GetPlayerIndex() int32 {
	if x != nil {
		return x.PlayerIndex
	}
	return 0
}

type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BallX         float64                `protobuf:"fixed64,1,opt,name=ball_x,json=ballX,proto3" json:"ball_x,omitempty"`
	BallY         float64                `protobuf:"fixed64,2,opt,name=ball_y,json=ballY,proto3" json:"ball_y,omitempty"`
	Paddle1Y      float64                `protobuf:"fixed64,3,opt,name=paddle1_y,json=paddle1Y,proto3" json:"paddle1_y,omitempty"`
	Paddle2Y      float64                `protobuf:"fixed64,4,opt,name=paddle2_y,json=paddle2Y,proto3" json:"paddle2_y,omitempty"`
	Score1        int32                  `protobuf:"varint,5,opt,name=score1,proto3" json:"score1,omitempty"`
	Score2        int32                  `protobuf:"varint,6,opt,name=score2,proto3" json:"score2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_pong_v1_pong_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_pong_v1_pong_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_pong_v1_pong_proto_rawDescGZIP(), []int{5}
}

func (x *GameState) GetBallX() float64 {
	if x != nil {
		return x.BallX
	}
	return 0
}

func (x *GameState) GetBallY() float64 {
	if x != nil {
		return x.BallY
	}
	return 0
}

func (x *GameState) GetPaddle1Y() float64 {
	if x != nil {
		return x.Paddle1Y
	}
	return 0
}

func (x *GameState) GetPaddle2Y() float64 {
	if x != nil {
		return x.Paddle2Y
	}
	return 0
}

func (x *GameState) GetScore1() int32 {
	if x != nil {
		return x.Score1
	}
	return 0
}

func (x *GameState) GetScore2() int32 {
	if x != nil {
		return x.Score2
	}
	return 0
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_pong_v1_pong_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pong_v1_pong_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_pong_v1_pong_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pong_v1_pong_proto protoreflect.FileDescriptor

const file_pong_v1_pong_proto_rawDesc = "" +
	"\n" +
	"\x12pong/v1/pong.proto\x12\apong.v1\"t\n" +
	"\rClientMessage\x12*\n" +
	"\x04join\x18\x01 \x01(\v2\x14.pong.v1.JoinRequestH\x00R\x04join\x12,\n" +
	"\x05input\x18\x02 \x01(\v2\x14.pong.v1.PaddleInputH\x00R\x05inputB\t\n" +
	"\apayload\"&\n" +
	"\vJoinRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"?\n" +
	"\vPaddleInput\x120\n" +
	"\tdirection\x18\x01 \x01(\x0e2\x12.pong.v1.DirectionR\tdirection\"\xa6\x01\n" +
	"\rServerMessage\x12/\n" +
	"\x06joined\x18\x01 \x01(\v2\x15.pong.v1.JoinResponseH\x00R\x06joined\x12*\n" +
	"\x05state\x18\x02 \x01(\v2\x12.pong.v1.GameStateH\x00R\x05state\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x15.pong.v1.ErrorMessageH\x00R\x05errorB\t\n" +
	"\apayload\"J\n" +
	"\fJoinResponse\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12!\n" +
	"\fplayer_index\x18\x02 \x01(\x05R\vplayerIndex\"\xa3\x01\n" +
	"\tGameState\x12\x15\n" +
	"\x06ball_x\x18\x01 \x01(\x01R\x05ballX\x12\x15\n" +
	"\x06ball_y\x18\x02 \x01(\x01R\x05ballY\x12\x1b\n" +
	"\tpaddle1_y\x18\x03 \x01(\x01R\bpaddle1Y\x12\x1b\n" +
	"\tpaddle2_y\x18\x04 \x01(\x01R\bpaddle2Y\x12\x16\n" +
	"\x06score1\x18\x05 \x01(\x05R\x06score1\x12\x16\n" +
	"\x06score2\x18\x06 \x01(\x05R\x06score2\"(\n" +
	"\fErrorMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*`\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fDIRECTION_UP\x10\x01\x12\x12\n" +
	"\x0eDIRECTION_DOWN\x10\x02\x12\x12\n" +
	"\x0eDIRECTION_STOP\x10\x032I\n" +
	"\vPongService\x12:\n" +
	"\x04Play\x12\x16.pong.v1.ClientMessage\x1a\x16.pong.v1.ServerMessage(\x010\x01B5Z3github.com/geofpwhite/html_games_engine/pong/pongv1b\x06proto3"

var (
	file_pong_v1_pong_proto_rawDescOnce sync.Once
	file_pong_v1_pong_proto_rawDescData []byte
)

func file_pong_v1_pong_proto_rawDescGZIP() []byte {
	file_pong_v1_pong_proto_rawDescOnce.Do(func() {
		file_pong_v1_pong_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pong_v1_pong_proto_rawDesc), len(file_pong_v1_pong_proto_rawDesc)))
	})
	return file_pong_v1_pong_proto_rawDescData
}

var file_pong_v1_pong_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pong_v1_pong_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pong_v1_pong_proto_goTypes = []any{
	(Direction)(0),        // 0: pong.v1.Direction
	(*ClientMessage)(nil), // 1: pong.v1.ClientMessage
	(*JoinRequest)(nil),   // 2: pong.v1.JoinRequest
	(*PaddleInput)(nil),   // 3: pong.v1.PaddleInput
	(*ServerMessage)(nil), // 4: pong.v1.ServerMessage
	(*JoinResponse)(nil),  // 5: pong.v1.JoinResponse
	(*GameState)(nil),     // 6: pong.v1.GameState
	(*ErrorMessage)(nil),  // 7: pong.v1.ErrorMessage
}
var file_pong_v1_pong_proto_depIdxs = []int32{
	2, // 0: pong.v1.ClientMessage.join:type_name -> pong.v1.JoinRequest
	3, // 1: pong.v1.ClientMessage.input:type_name -> pong.v1.PaddleInput
	0, // 2: pong.v1.PaddleInput.direction:type_name -> pong.v1.Direction
	5, // 3: pong.v1.ServerMessage.joined:type_name -> pong.v1.JoinResponse
	6, // 4: pong.v1.ServerMessage.state:type_name -> pong.v1.GameState
	7, // 5: pong.v1.ServerMessage.error:type_name -> pong.v1.ErrorMessage
	1, // 6: pong.v1.PongService.Play:input_type -> pong.v1.ClientMessage
	4, // 7: pong.v1.PongService.Play:output_type -> pong.v1.ServerMessage
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pong_v1_pong_proto_init() }
func file_pong_v1_pong_proto_init() {
	if File_pong_v1_pong_proto != nil {
		return
	}
	file_pong_v1_pong_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Join)(nil),
		(*ClientMessage_Input)(nil),
	}
	file_pong_v1_pong_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerMessage_Joined)(nil),
		(*ServerMessage_State)(nil),
		(*ServerMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pong_v1_pong_proto_rawDesc), len(file_pong_v1_pong_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pong_v1_pong_proto_goTypes,
		DependencyIndexes: file_pong_v1_pong_proto_depIdxs,
		EnumInfos:         file_pong_v1_pong_proto_enumTypes,
		MessageInfos:      file_pong_v1_pong_proto_msgTypes,
	}.Build()
	File_pong_v1_pong_proto = out.File
	file_pong_v1_pong_proto_goTypes = nil
	file_pong_v1_pong_proto_depIdxs = nil
}
